### ISSUE TITLE
Diagrama de casos de uso en GenMymodel

### ISSUE THREAD

**Issue by matias-martinezm** [ProyectosEAFIT/AplicacionHibrida#16]
Realice un diagrama de casos de uso del sistema, usando la herramienta GenMyModel

**Comment by matias-martinezm** [comment]
Consultar ejemplos: 

https://sparxsystems.com/resources/tutorials/uml2/use-case-diagram.html

**Comment by ViVi09030** [comment]
![usecase-diagram](https://github.com/ProyectosEAFIT/AplicacionHibrida/assets/159188826/1b0334d2-a0da-4e0d-ba5f-0270484a6899)
Link: https://app.genmymodel.com/api/projects/_D2p8gObaEe6YcvViuOreEw/diagrams/_D2p8g-baEe6YcvViuOreEw/svg
